const Joi = require('joi');
//Joi.objectId = require('joi-objectid')(Joi);
const mongoose = require('mongoose');
const express = require('express');
const config = require('config');
const app = express();
require('./startup/routes')(app);
require('./startup/db')();
const port = process.env.PORT||3000;
app.listen(port,()=>console.log(`Listening on port ${port}....`));